import os
import pandas as pd

configfile: "config/config.yaml"
samples = pd.read_table(config["samples"], index_col = "sample")

rule all:
    input:
        "results/phylogeny/newick_tree.png", "results/mlst/mlst.tsv" if config["mlst"]["execution"] == "yes" else [], "results/antibiotic_resistance_genes/heatmap.png" if config["antibiotic_resistance_genes"]["execution"] == "yes" else [], "results/multiqc/multiqc_qc.html", "results/multiqc/multiqc_contamination.html" if config["contamination_filter"]["execution"] == "yes" and config["assembly_type"] == "de_novo" else [], expand("results/assembly_statistics/{Sample}/report.txt", Sample=list(samples.index)), "results/multiqc/multiqc_assembly.html"

include: "rules/qc.smk"
include: "rules/contamination_filter.smk"
include: "rules/de_novo_assembly.smk"
include: "rules/assembly_stats.smk"
include: "rules/reference_based_assembly.smk"
include: "rules/annotation.smk"
include: "rules/mlst.smk"
include: "rules/core_genome_alignment.smk"
include: "rules/phylogeny.smk"
include: "rules/antibiotic_resistance_genes.smk"
