samples: "path/to/samples"
reference_genome: "path/to/reference"
assembly_type: ""  #Options: de_novo/reference_based

trimmomatic:
  sliding_window:
    window_size: "4"
    requiredQuality: "15"
  minlen: "40"  
  adapters: "path/to/adapters" #optional

contamination_filter:
  execution: "" #Options: yes/no
  kraken2_database: "path/to/kraken2_database"
  krakentools:
    taxonomy_IDs: "" #space separated list of taxonomy IDs
    filter_type: "positive" #Options: positive/negative; positive = include IDs/negative = exclude IDs
    include_parents: "no" #Options: yes/no; consider parents of IDs in filtering - optional
    include_children: "no" #Options: yes/no; consider children of IDs in filtering - optional

prokka:
  genus: "" #genus name - optional
  species: ""#species name - optional
  extra: ""

roary:
  alignment_type: "fast" #Options: fast/accurate
  extra: ""

phylogeny:
  outgroup: "path/to/outgroup" #optional
  outgroup_sample_name: "" #name for the outgroup - optional (mandatory if outgroup desired)
  blacklist:  "" #comma separated list of Samples to exclude from phylogeny; do not use spaces after a commas! - optional
  bs_trees: "50" # number of boosting trees used
  extra: ""

mlst:
  execution: "yes" #Options: yes/no
  scheme: "" #PubMLST scheme name - optional
  extra: ""

antibiotic_resistance_genes:
  execution: "yes" #Options: yes/no
  card_database: "path/to/card_database" #optional
  extra: ""
